In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected_temperature = temperature + 2
print("Corrected temperatures:", corrected_temperature)

fahrenheit = (9/5) * corrected_temperature + 32
print("Temperatures in Fahrenheit:", fahrenheit)

readings_greater_32 = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:", readings_greater_32)

count = np.sum(corrected_temperature > 32)
print("Number of readings exceeding 32°C:", count)

Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings exceeding 32°C: 5


In [7]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7000, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

total_steps = np.sum(steps)
print("Total steps:", total_steps)

mean_steps = round(np.mean(steps), 2)
print("Mean steps:", mean_steps)

maximum = np.max(steps)
minimum = np.min(steps)
print("Maximum steps:", maximum)
print("Minimum steps:", minimum)

daily_total = np.sum(steps, axis=0)
print("Total steps for each day:", daily_total)

user_total = np.sum(steps, axis=1)
print("Total steps for each user:", user_total)

max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum value:", max_position)

Total steps: 83700
Mean steps: 6975.0
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 26800 30400]
Total steps for each user: [18300 24000 14400 27000]
Position of maximum value: (np.int64(3), np.int64(2))


In [8]:
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]

subset[0] = 900

print("After modifying subset:")
print("Original:", original)
print("Subset:", subset)

copied = original[1:5].copy()
copied[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied:", copied)

matrix = np.arange(1, 13).reshape(3, 4)

print("\n3 x 4 Matrix:")
print(matrix)

first_row = matrix[0, :]
print("\nFirst row:", first_row)

last_row = matrix[-1, :]
print("Last row:", last_row)

second_column = matrix[:, 1]
print("Second column:", second_column)

selected_elements = matrix[1:3, 2:4]
print("Rows 1-2 and columns 2-3:")
print(selected_elements)

flattened = matrix.flatten()
raveled = matrix.ravel()

print("\nFlatten:", flattened)
print("Ravel:", raveled)

raveled[0] = 1000

print("\nAfter modifying ravel:")
print("Matrix:")
print(matrix)
print("Raveled:", raveled)

flattened[1] = 2000

print("\nAfter modifying flatten:")
print("Matrix:")
print(matrix)
print("Flattened:", flattened)

print("\nShape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

After modifying subset:
Original: [  1 900   3   4   5   6]
Subset: [900   3   4   5]

After modifying copied array:
Original: [  1 900   3   4   5   6]
Copied: [500   3   4   5]

3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
Matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Raveled: [1000    2    3    4    5    6    7    8    9   10   11   12]

After modifying flatten:
Matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Flattened: [   1 2000    3    4    5    6    7    8    9   10   11   12]

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [9]:
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

XT = X.T
print("\nX.T:")
print(XT)

XT_X = X.T @ X
print("\nX.T @ X:")
print(XT_X)

inverse = np.linalg.inv(XT_X)
print("\nInverse of X.T @ X:")
print(inverse)

beta = np.linalg.inv(X.T @ X) @ X.T @ y

print("\nOLS coefficients:")
print(beta)

print("\nCoefficients:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta

print("\nNew user:", new_user)
print("Predicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2

X.T:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS coefficients:
[-0.15921454  0.14083853 10.06302242]

Coefficients:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587

New user: [ 5 40  7]
Predicted assistance score: 75.27862544779117
