In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original array:", arr)

print("After adding 2:", arr + 2)

print("After multiplying by 3:", arr * 3)

print("After dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

print("Original array:", arr)
print("Reversed array:", arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("\nArray x:", x)
print("Most frequent value:", most_frequent)
print("Indices:", indices)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("\nArray y:", y)
print("Most frequent value:", most_frequent)
print("Indices:", indices)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Indices: [0 5 7 8 9]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Indices: [0 1 2]


In [ ]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("1st row, 2nd column:", arr[0, 1])

print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [ ]:
import numpy as np

Amatya_Simba = np.linspace(10, 100, 25)

print("Array:")
print(Amatya_Simba)

print("Dimensions:", Amatya_Simba.ndim)
print("Shape:", Amatya_Simba.shape)
print("Total elements:", Amatya_Simba.size)
print("Data type:", Amatya_Simba.dtype)
print("Total bytes:", Amatya_Simba.nbytes)

transpose_array = Amatya_Simba.reshape(1, 25)

print("Transpose using reshape():")
print(transpose_array)

transpose_T = Amatya_Simba.T

print("Transpose using T attribute:")
print(transpose_T)

print("Can we do the same with T attribute? Yes, but for a 1-D array, T does not change its shape.")

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
Transpose using T attribute:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Can we do the same with T attribute? Yes, but for a 1-D array, T does not change its shape.


In [7]:
import numpy as np

ucs420_Amatya_Simba = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 25, 35]
])

print("Original array:")
print(ucs420_Amatya_Simba)

print("Mean:", np.mean(ucs420_Amatya_Simba))

print("Median:", np.median(ucs420_Amatya_Simba))

print("Maximum:", np.max(ucs420_Amatya_Simba))

print("Minimum:", np.min(ucs420_Amatya_Simba))

print("Unique elements:", np.unique(ucs420_Amatya_Simba))

reshaped_ucs420_Amatya_Simba = ucs420_Amatya_Simba.reshape(4, 3)

print("\nReshaped array (4 x 3):")
print(reshaped_ucs420_Amatya_Simba)

resized_ucs420_Amatya_Simba = np.resize(ucs420_Amatya_Simba, (2, 3))

print("\nResized array (2 x 3):")
print(resized_ucs420_Amatya_Simba)

Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 25 35]]
Mean: 43.75
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 25 30 35 40 50 60 70 80 90]

Reshaped array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 25 35]]

Resized array (2 x 3):
[[10 20 30]
 [40 50 60]]
